[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/tuyensinh"
  status = 301

[[redirects]]
  from = "/*"
  to = "/baiviet"
  status = 301

[[redirects]]
  from = "/"
  to = "/timkiem"
  query = { q = ":keyword" }
  status = 301