[[redirects]]
  from = "/*"
  to = "/tuyensinh"
  status = 301

[[redirects]]
  from = "/*"
  to = "/timkiem?q=:keyword"
  status = 301

[[redirects]]
  from = "/*"
  to = "/baiviet"
  status = 301

[[redirects]]
  from = "/*"
  to = "/daotao/dao-tao"
  status = 301

[[redirects]]
  from = "/*"
  to = "/daotao/dai-hoc"
  status = 301

[[redirects]]
  from = "/*"
  to = "/daotao/cao-dang"
  status = 301
